# Hand written digit recognition using kNN


# Importing the dataset

The dataset is a modified version of the “Optical Recognition of Handwritten Digits Data Set” by E. Alpaydin,
C. Kaynak, Department of Computer Engineering at Bogazici University, 80815 Istanbul Turkey, retrieved
from the UCI Machine Learning Repository (http://archive.ics.uci.edu/ml) on October 3, 2010. You can get the dataset from here https://github.com/TarunNanduri/Artificial-Intelligence/kNN-DigitRecognition/dataset/

In [1]:
from os import listdir
for name in listdir('./dataset/'):
    print(name)

testDigits
trainingDigits


In [2]:
for file in listdir('./dataset/trainingDigits'):
    print(file)

0_0.txt
0_1.txt
0_10.txt
0_100.txt
0_101.txt
0_102.txt
0_103.txt
0_104.txt
0_105.txt
0_106.txt
0_107.txt
0_108.txt
0_109.txt
0_11.txt
0_110.txt
0_111.txt
0_112.txt
0_113.txt
0_114.txt
0_115.txt
0_116.txt
0_117.txt
0_118.txt
0_119.txt
0_12.txt
0_120.txt
0_121.txt
0_122.txt
0_123.txt
0_124.txt
0_125.txt
0_126.txt
0_127.txt
0_128.txt
0_129.txt
0_13.txt
0_130.txt
0_131.txt
0_132.txt
0_133.txt
0_134.txt
0_135.txt
0_136.txt
0_137.txt
0_138.txt
0_139.txt
0_14.txt
0_140.txt
0_141.txt
0_142.txt
0_143.txt
0_144.txt
0_145.txt
0_146.txt
0_147.txt
0_148.txt
0_149.txt
0_15.txt
0_150.txt
0_151.txt
0_152.txt
0_153.txt
0_154.txt
0_155.txt
0_156.txt
0_157.txt
0_158.txt
0_159.txt
0_16.txt
0_160.txt
0_161.txt
0_162.txt
0_163.txt
0_164.txt
0_165.txt
0_166.txt
0_167.txt
0_168.txt
0_169.txt
0_17.txt
0_170.txt
0_171.txt
0_172.txt
0_173.txt
0_174.txt
0_175.txt
0_176.txt
0_177.txt
0_178.txt
0_179.txt
0_18.txt
0_180.txt
0_181.txt
0_182.txt
0_183.txt
0_184.txt
0_185.txt
0_186.txt
0_187.txt
0_188.txt
0_19.txt
0_2.

5_107.txt
5_108.txt
5_109.txt
5_11.txt
5_110.txt
5_111.txt
5_112.txt
5_113.txt
5_114.txt
5_115.txt
5_116.txt
5_117.txt
5_118.txt
5_119.txt
5_12.txt
5_120.txt
5_121.txt
5_122.txt
5_123.txt
5_124.txt
5_125.txt
5_126.txt
5_127.txt
5_128.txt
5_129.txt
5_13.txt
5_130.txt
5_131.txt
5_132.txt
5_133.txt
5_134.txt
5_135.txt
5_136.txt
5_137.txt
5_138.txt
5_139.txt
5_14.txt
5_140.txt
5_141.txt
5_142.txt
5_143.txt
5_144.txt
5_145.txt
5_146.txt
5_147.txt
5_148.txt
5_149.txt
5_15.txt
5_150.txt
5_151.txt
5_152.txt
5_153.txt
5_154.txt
5_155.txt
5_156.txt
5_157.txt
5_158.txt
5_159.txt
5_16.txt
5_160.txt
5_161.txt
5_162.txt
5_163.txt
5_164.txt
5_165.txt
5_166.txt
5_167.txt
5_168.txt
5_169.txt
5_17.txt
5_170.txt
5_171.txt
5_172.txt
5_173.txt
5_174.txt
5_175.txt
5_176.txt
5_177.txt
5_178.txt
5_179.txt
5_18.txt
5_180.txt
5_181.txt
5_182.txt
5_183.txt
5_184.txt
5_185.txt
5_186.txt
5_19.txt
5_2.txt
5_20.txt
5_21.txt
5_22.txt
5_23.txt
5_24.txt
5_25.txt
5_26.txt
5_27.txt
5_28.txt
5_29.txt
5_3.txt
5_30.txt
5_31

The files are of text format and each digit contains nearly 200 files

# Let's check how the file looks like

In [3]:
digit = open("./dataset/trainingDigits/0_13.txt", "r")
for line in digit.readlines():
    print(line)

00000000000000011100000000000000

00000000000001111110000000000000

00000000000011111111000000000000

00000000000001111111100000000000

00000000000011111111110000000000

00000000000111111111110000000000

00000001100111111001111000000000

00000001111111110001111100000000

00000011111111000000011100000000

00000011111111000000011100000000

00000011111111000000001100000000

00000011111111000000000110000000

00000011111111000000000110000000

00000011111111000000000110000000

00000011100110000000000110000000

00000001110011000000000111000000

00000001100000000000000111000000

00000001110000000000000111000000

00000000111000000000000111100000

00000001111000000000000111000000

00000001111000000000001111000000

00000000111000000000011110000000

00000000011100000000001111000000

00000000011110000000011111000000

00000000011111000000111100000000

00000000001110000011111100000000

00000000000111111111111100000000

00000000000111111111111000000000

00000000000111111111111000000000

00000000000011

# Spliting data

The data is already split into "testDigits" and "trainingDigits".So, we need just need to make them suitable to build model.

## Pre-processing dataset

Our dataset is in the form of 32*32 image.In order to train the model, we need to convert our 32*32 image into (1,1024) NumPy array.

In [4]:
from numpy import zeros

def img2vector(filename):
#     imgVector = zeros((1,1024))
    imgVector = []
    file = open(filename)
    for i in range(32):
        lineStr = file.readline()
        for j in range(32):
            imgVector.append(int(lineStr[j]))
#     print(imgVector)
    return imgVector

In [5]:
trainData = './dataset/trainingDigits'
trainingFiles = listdir(trainData)
trainDigits = []
trainLabels = []
for file in trainingFiles:
    trainDigits.append(img2vector(trainData+'/'+file))
    
    trainLabels.append(int(file[0]))
# print(trainDigits)

In [6]:
print(trainLabels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

### Our train data is ready. Now, let's make our test data ready.

In [7]:
testData = './dataset/testDigits'
testingFiles = listdir(testData)
testDigits = []
testLabels = []
for file in testingFiles:
    testDigits.append(img2vector(testData+'/'+file))
    testLabels.append(int(file[0]))
# print(testDigits)

In [8]:
print(testLabels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 

### Now the data is ready for building a model. So, let's start build our model 

# Building the model

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

knn.fit(trainDigits,trainLabels)
trainScore = knn.score(trainDigits,trainLabels)

print(trainScore)

0.9819027921406411


Whooohh! That was a great accuracy.Now let's see how our model behaves on unseen data.

## Testing the model

In [10]:
pred = knn.predict(testDigits)

## Evaluating Model

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:\n")
print(confusion_matrix(testLabels,pred))
print("\nClassification Report:\n")
print(classification_report(testLabels,pred))


Confusion Matrix:

[[ 87   0   0   0   0   0   0   0   0   0]
 [  0  96   0   0   0   0   0   1   0   0]
 [  0   0  92   0   0   0   0   0   0   0]
 [  0   0   0  83   0   0   0   0   1   1]
 [  1   0   0   0 113   0   0   0   0   0]
 [  0   0   0   1   0 106   0   0   0   1]
 [  0   0   0   0   0   0  87   0   0   0]
 [  0   0   0   0   0   0   0  96   0   0]
 [  0   5   0   2   0   0   1   0  83   0]
 [  0   1   0   1   0   1   0   1   0  85]]

Classification Report:

              precision    recall  f1-score   support

           0       0.99      1.00      0.99        87
           1       0.94      0.99      0.96        97
           2       1.00      1.00      1.00        92
           3       0.95      0.98      0.97        85
           4       1.00      0.99      1.00       114
           5       0.99      0.98      0.99       108
           6       0.99      1.00      0.99        87
           7       0.98      1.00      0.99        96
           8       0.99      0.91     

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(testLabels,pred)

0.9809725158562368

## Our model has an accuracy of 0.98